update=8/7/2014 11:53:30 AM
last_client=pcbnew
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[eeschema]
version=1
LibDir=
NetFmtName=PcbnewAdvanced
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=special
LibName13=microcontrollers
LibName14=C:/Program Files/KiCad/share/modules/xbee/module_droids/modules_droids
LibName15=dsp
LibName16=microchip
LibName17=analog_switches
LibName18=motorola
LibName19=texas
LibName20=intel
LibName21=audio
LibName22=interface
LibName23=digital-audio
LibName24=philips
LibName25=display
LibName26=cypress
LibName27=siliconi
LibName28=ANDON-cache
LibName29=opto
LibName30=atmel
LibName31=contrib
LibName32=valves
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=4.000000000000
PadDrillOvalY=4.000000000000
PadSizeH=4.000000000000
PadSizeV=4.000000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[pcbnew/libraries]
LibDir=../../ANDON
LibName1=terminal_block/w_conn_gmkds
LibName2=sockets
LibName3=connect
LibName4=discret
LibName5=pin_array
LibName6=divers
LibName7=smd_capacitors
LibName8=smd_resistors
LibName9=smd_crystal&oscillator
LibName10=smd_dil
LibName11=smd_transistors
LibName12=libcms
LibName13=display
LibName14=led
LibName15=dip_sockets
LibName16=pga_sockets
LibName17=C:/Program Files/KiCad/share/library/1wire
LibName18=C:/Program Files/KiCad/share/library/3M
LibName19=C:/Program Files/KiCad/share/library/7sh
LibName20=C:/Program Files/KiCad/share/library/20f001n
LibName21=C:/Program Files/KiCad/share/library/29le010
LibName22=C:/Program Files/KiCad/share/library/40xx
LibName23=C:/Program Files/KiCad/share/library/65xxx
LibName24=C:/Program Files/KiCad/share/library/74ah
LibName25=C:/Program Files/KiCad/share/library/74hc(t)4046
LibName26=C:/Program Files/KiCad/share/library/74xx-eu
LibName27=C:/Program Files/KiCad/share/library/74xx-little-us
LibName28=C:/Program Files/KiCad/share/library/78xx_with_heatsink
LibName29=C:/Program Files/KiCad/share/library/648a40-01-tsop40--14mm
LibName30=C:/Program Files/KiCad/share/library/751xx
LibName31=C:/Program Files/KiCad/share/library/abi-lcd
LibName32=C:/Program Files/KiCad/share/library/ad
LibName33=C:/Program Files/KiCad/share/library/ad620
LibName34=C:/Program Files/KiCad/share/library/ad624
LibName35=C:/Program Files/KiCad/share/library/ad633
LibName36=C:/Program Files/KiCad/share/library/ad725
LibName37=C:/Program Files/KiCad/share/library/ad7709
LibName38=C:/Program Files/KiCad/share/library/ad7710
LibName39=C:/Program Files/KiCad/share/library/ad8018
LibName40=C:/Program Files/KiCad/share/library/ad9235
LibName41=C:/Program Files/KiCad/share/library/ad9834
LibName42=C:/Program Files/KiCad/share/library/ad9851
LibName43=C:/Program Files/KiCad/share/library/ad22151
LibName44=C:/Program Files/KiCad/share/library/ad74111_adg3304
LibName45=C:/Program Files/KiCad/share/library/adns-2610
LibName46=C:/Program Files/KiCad/share/library/ads11xx
LibName47=C:/Program Files/KiCad/share/library/aduc816
LibName48=C:/Program Files/KiCad/share/library/aduc841
LibName49=C:/Program Files/KiCad/share/library/adv7202
LibName50=C:/Program Files/KiCad/share/library/advsocket-computer
LibName51=C:/Program Files/KiCad/share/library/adxl
LibName52=C:/Program Files/KiCad/share/library/adxl103_203e
LibName53=C:/Program Files/KiCad/share/library/adxl311
LibName54=C:/Program Files/KiCad/share/library/adxl320
LibName55=C:/Program Files/KiCad/share/library/adxrs300
LibName56=C:/Program Files/KiCad/share/library/agilent-infrared
LibName57=C:/Program Files/KiCad/share/library/akm
LibName58=C:/Program Files/KiCad/share/library/allegro
LibName59=C:/Program Files/KiCad/share/library/alps_blue_rk-27_single
LibName60=C:/Program Files/KiCad/share/library/altera
LibName61=C:/Program Files/KiCad/share/library/altera-2
LibName62=C:/Program Files/KiCad/share/library/altera-cycloneii
LibName63=C:/Program Files/KiCad/share/library/altera-ep3c40f484
LibName64=C:/Program Files/KiCad/share/library/amber_bnc_iv
LibName65=C:/Program Files/KiCad/share/library/AMD_ELAN_SC_520
LibName66=C:/Program Files/KiCad/share/library/amd_taxi
LibName67=C:/Program Files/KiCad/share/library/amd-mach
LibName68=C:/Program Files/KiCad/share/library/am-hrrn-xxx
LibName69=C:/Program Files/KiCad/share/library/amphenol-simlock
LibName70=C:/Program Files/KiCad/share/library/anadigm-1
LibName71=C:/Program Files/KiCad/share/library/analog_device_adxl202e
LibName72=C:/Program Files/KiCad/share/library/analog_devices_gaui
LibName73=C:/Program Files/KiCad/share/library/analog-devices
LibName74=C:/Program Files/KiCad/share/library/analog-devices2
LibName75=C:/Program Files/KiCad/share/library/analog-devices-current-shunt-monitors
LibName76=C:/Program Files/KiCad/share/library/analog-devices-dds
LibName77=C:/Program Files/KiCad/share/library/ap_lna
LibName78=C:/Program Files/KiCad/share/library/ap_mixernew
LibName79=C:/Program Files/KiCad/share/library/ap_rc_0402
LibName80=C:/Program Files/KiCad/share/library/ap_saw
LibName81=C:/Program Files/KiCad/share/library/ap_transformer
LibName82=C:/Program Files/KiCad/share/library/ap_vco
LibName83=C:/Program Files/KiCad/share/library/asix
LibName84=C:/Program Files/KiCad/share/library/at89x52
LibName85=C:/Program Files/KiCad/share/library/at90can128
LibName86=C:/Program Files/KiCad/share/library/at91sam7sxxx-au
LibName87=C:/Program Files/KiCad/share/library/at91sam9261
LibName88=C:/Program Files/KiCad/share/library/atarilynx
LibName89=C:/Program Files/KiCad/share/library/atf1502als
LibName90=C:/Program Files/KiCad/share/library/atmega8
LibName91=C:/Program Files/KiCad/share/library/atmel
LibName92=C:/Program Files/KiCad/share/library/atmel_prototype_header
LibName93=C:/Program Files/KiCad/share/library/atmel-1
LibName94=C:/Program Files/KiCad/share/library/atmel89cxxxx
LibName95=C:/Program Files/KiCad/share/library/atmel-2005
LibName96=C:/Program Files/KiCad/share/library/attiny13
LibName97=C:/Program Files/KiCad/share/library/attiny24_44_84
LibName98=C:/Program Files/KiCad/share/library/aurel
LibName99=C:/Program Files/KiCad/share/library/avr
LibName100=C:/Program Files/KiCad/share/library/avr-1
LibName101=C:/Program Files/KiCad/share/library/avr-2
LibName102=C:/Program Files/KiCad/share/library/avr-3
LibName103=C:/Program Files/KiCad/share/library/avr-4
LibName104=C:/Program Files/KiCad/share/library/avr32
LibName105=C:/Program Files/KiCad/share/library/axis
LibName106=C:/Program Files/KiCad/share/library/basic_stamps
LibName107=C:/Program Files/KiCad/share/library/basicstamp2
LibName108=C:/Program Files/KiCad/share/library/basicx
LibName109=C:/Program Files/KiCad/share/library/basicx_chips
LibName110=C:/Program Files/KiCad/share/library/bluegiga
LibName111=C:/Program Files/KiCad/share/library/blueradio-br-sc30a
LibName112=C:/Program Files/KiCad/share/library/bourns
LibName113=C:/Program Files/KiCad/share/library/burr-brown
LibName114=C:/Program Files/KiCad/share/library/burr-brown-2
LibName115=C:/Program Files/KiCad/share/library/burr-brown-3
LibName116=C:/Program Files/KiCad/share/library/burr-brown-ads8341
LibName117=C:/Program Files/KiCad/share/library/butterfly9
LibName118=C:/Program Files/KiCad/share/library/bv_20
LibName119=C:/Program Files/KiCad/share/library/bx_24
LibName120=C:/Program Files/KiCad/share/library/californiamicro
LibName121=C:/Program Files/KiCad/share/library/calmicro
LibName122=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKM2-100v
LibName123=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKM2-250v
LibName124=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKM2-400v
LibName125=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKM3-160v
LibName126=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKM3-250v
LibName127=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKM3-400v
LibName128=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP1-400v
LibName129=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP1-630v
LibName130=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP1-1000v
LibName131=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP1-1250v
LibName132=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP1-1600v
LibName133=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP1-2000v
LibName134=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP1-4000v
LibName135=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP1-6000v
LibName136=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP2-63v
LibName137=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP2-100v
LibName138=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP2-250v
LibName139=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP2-400v
LibName140=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP2-630v
LibName141=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP2-800v
LibName142=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP2-1000v
LibName143=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP3-100v
LibName144=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP3-160v
LibName145=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP3-250v
LibName146=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP3-400v
LibName147=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP3-630v
LibName148=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKP3-1000v
LibName149=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKS2-100v
LibName150=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKS2-250v
LibName151=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKS2-400v
LibName152=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKS3-100v
LibName153=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKS3-160v
LibName154=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKS3-250v
LibName155=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKS3-400v
LibName156=C:/Program Files/KiCad/share/library/Capacitor-Wima-FKS3-630v
LibName157=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKM2-100v
LibName158=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKM2-250v
LibName159=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKM4-250v
LibName160=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKM4-400v
LibName161=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP2-100v
LibName162=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP2-250v
LibName163=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP2-400v
LibName164=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP2-630v
LibName165=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP4-250v
LibName166=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP4-400v
LibName167=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP4-630v
LibName168=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP4-1000v
LibName169=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP10-160v
LibName170=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP10-250v
LibName171=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP10-400v
LibName172=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP10-630v
LibName173=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP10-1000v
LibName174=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP10-1600v
LibName175=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKP10-2000v
LibName176=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS02-50v
LibName177=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS02-63v
LibName178=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS02-100v
LibName179=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS2-16v
LibName180=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS2-50v
LibName181=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS2-63v
LibName182=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS2-100v
LibName183=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS2-250v
LibName184=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS2-400v
LibName185=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS4-50v
LibName186=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS4-63v
LibName187=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS4-100v
LibName188=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS4-250v
LibName189=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS4-400v
LibName190=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS4-630v
LibName191=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS4-1000v
LibName192=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS4-1500v
LibName193=C:/Program Files/KiCad/share/library/Capacitor-Wima-MKS4-2000v
LibName194=C:/Program Files/KiCad/share/library/Capacitor-Wima-MP3-X2-250v
LibName195=C:/Program Files/KiCad/share/library/Capacitor-Wima-MP3-X2-275v
LibName196=C:/Program Files/KiCad/share/library/Capacitor-Wima-MP3-Y2-250v
LibName197=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD1812-63v
LibName198=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD1812-100v
LibName199=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD1812-250v
LibName200=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD2020-63v
LibName201=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD2020-100v
LibName202=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD2020-250v
LibName203=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD2824-63v
LibName204=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD2824-100v
LibName205=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD2824-250v
LibName206=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD4036-40v
LibName207=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD4036-63v
LibName208=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD4036-100v
LibName209=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD4036-250v
LibName210=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD4036-400v
LibName211=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD4036-630v
LibName212=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD5045-40v
LibName213=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD5045-63v
LibName214=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD5045-100v
LibName215=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD5045-250v
LibName216=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD5045-400v
LibName217=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD5045-630v
LibName218=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD5045-1000v
LibName219=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD6560-40v
LibName220=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD6560-63v
LibName221=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD6560-100v
LibName222=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD6560-250v
LibName223=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD6560-400v
LibName224=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD6560-630v
LibName225=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD6560-1000v
LibName226=C:/Program Files/KiCad/share/library/Capacitor-Wima-SMD-MP3-Y2-250v
LibName227=C:/Program Files/KiCad/share/library/CapAudyn
LibName228=C:/Program Files/KiCad/share/library/Cap-Audyn-Sn
LibName229=C:/Program Files/KiCad/share/library/Cap-Dreh
LibName230=C:/Program Files/KiCad/share/library/Cap-Gold
LibName231=C:/Program Files/KiCad/share/library/Cap-M
LibName232=C:/Program Files/KiCad/share/library/cap-master
LibName233=C:/Program Files/KiCad/share/library/Cap-M-Supreme
LibName234=C:/Program Files/KiCad/share/library/Cap-M-ZN
LibName235=C:/Program Files/KiCad/share/library/cap-pan
LibName236=C:/Program Files/KiCad/share/library/cap-pan40
LibName237=C:/Program Files/KiCad/share/library/CapSiem
LibName238=C:/Program Files/KiCad/share/library/cap-vishay-153clv
LibName239=C:/Program Files/KiCad/share/library/c-control
LibName240=C:/Program Files/KiCad/share/library/chipcon
LibName241=C:/Program Files/KiCad/share/library/chipcon-ti
LibName242=C:/Program Files/KiCad/share/library/cirrus
LibName243=C:/Program Files/KiCad/share/library/cirrus-2
LibName244=C:/Program Files/KiCad/share/library/cirrus-3
LibName245=C:/Program Files/KiCad/share/library/cirrus-mpu
LibName246=C:/Program Files/KiCad/share/library/cirrus-v1.0.2
LibName247=C:/Program Files/KiCad/share/library/c-max
LibName248=C:/Program Files/KiCad/share/library/cml-micro
LibName249=C:/Program Files/KiCad/share/library/cny70
LibName250=C:/Program Files/KiCad/share/library/coldfire
LibName251=C:/Program Files/KiCad/share/library/comfile
LibName252=C:/Program Files/KiCad/share/library/computronics.com.au
LibName253=C:/Program Files/KiCad/share/library/con_conec
LibName254=C:/Program Files/KiCad/share/library/con_nokia
LibName255=C:/Program Files/KiCad/share/library/con-amp
LibName256=C:/Program Files/KiCad/share/library/con-amphenol
LibName257=C:/Program Files/KiCad/share/library/con-amp-micromatch
LibName258=C:/Program Files/KiCad/share/library/con-cpci
LibName259=C:/Program Files/KiCad/share/library/con-cuistack
LibName260=C:/Program Files/KiCad/share/library/con-cypressindustries
LibName261=C:/Program Files/KiCad/share/library/con-erni
LibName262=C:/Program Files/KiCad/share/library/con-faston
LibName263=C:/Program Files/KiCad/share/library/con-fujitsu-pcmcia
LibName264=C:/Program Files/KiCad/share/library/con-gr47_gsm_module
LibName265=C:/Program Files/KiCad/share/library/con-harting-ml
LibName266=C:/Program Files/KiCad/share/library/con-hdrs40
LibName267=C:/Program Files/KiCad/share/library/con-headers-jp
LibName268=C:/Program Files/KiCad/share/library/con-hirose
LibName269=C:/Program Files/KiCad/share/library/con-hirose-df12d(3.0)60dp0.5v80
LibName270=C:/Program Files/KiCad/share/library/con-jack
LibName271=C:/Program Files/KiCad/share/library/con-jst2
LibName272=C:/Program Files/KiCad/share/library/con-molex
LibName273=C:/Program Files/KiCad/share/library/con-molex-2
LibName274=C:/Program Files/KiCad/share/library/connect
LibName275=C:/Program Files/KiCad/share/library/con-neutrik_ag
LibName276=C:/Program Files/KiCad/share/library/conn-hirose
LibName277=C:/Program Files/KiCad/share/library/con-omnetics
LibName278=C:/Program Files/KiCad/share/library/con-pci_express(pci-e)
LibName279=C:/Program Files/KiCad/share/library/con-phoenix-250
LibName280=C:/Program Files/KiCad/share/library/con-phoenix-381_l
LibName281=C:/Program Files/KiCad/share/library/con-phoenix-500-mstba6
LibName282=C:/Program Files/KiCad/share/library/con-ptr500+
LibName283=C:/Program Files/KiCad/share/library/con-pulse
LibName284=C:/Program Files/KiCad/share/library/conrad
LibName285=C:/Program Files/KiCad/share/library/con-ria182
LibName286=C:/Program Files/KiCad/share/library/con-riacon
LibName287=C:/Program Files/KiCad/share/library/con-subd
LibName288=C:/Program Files/KiCad/share/library/controller-micro_atmel_jd
LibName289=C:/Program Files/KiCad/share/library/con-usb
LibName290=C:/Program Files/KiCad/share/library/con-usb-2
LibName291=C:/Program Files/KiCad/share/library/con-usb-3
LibName292=C:/Program Files/KiCad/share/library/converter
LibName293=C:/Program Files/KiCad/share/library/con-vg
LibName294=C:/Program Files/KiCad/share/library/con-wago
LibName295=C:/Program Files/KiCad/share/library/con-yamaichi
LibName296=C:/Program Files/KiCad/share/library/con-yamaichi-cf
LibName297=C:/Program Files/KiCad/share/library/con-yamaichi-cf-2
LibName298=C:/Program Files/KiCad/share/library/crystal
LibName299=C:/Program Files/KiCad/share/library/crystal-epson
LibName300=C:/Program Files/KiCad/share/library/cts
LibName301=C:/Program Files/KiCad/share/library/cy7c1009b
LibName302=C:/Program Files/KiCad/share/library/cyan
LibName303=C:/Program Files/KiCad/share/library/cygnal
LibName304=C:/Program Files/KiCad/share/library/cygnal_mini
LibName305=C:/Program Files/KiCad/share/library/cypress-fx2
LibName306=C:/Program Files/KiCad/share/library/cypressmicro
LibName307=C:/Program Files/KiCad/share/library/dallas
LibName308=C:/Program Files/KiCad/share/library/dallas-1
LibName309=C:/Program Files/KiCad/share/library/dallas600
LibName310=C:/Program Files/KiCad/share/library/dallas-rtc
LibName311=C:/Program Files/KiCad/share/library/dcsocket
LibName312=C:/Program Files/KiCad/share/library/dframes
LibName313=C:/Program Files/KiCad/share/library/dicons
LibName314=C:/Program Files/KiCad/share/library/digital-transistors
LibName315=C:/Program Files/KiCad/share/library/diode
LibName316=C:/Program Files/KiCad/share/library/diode-1
LibName317=C:/Program Files/KiCad/share/library/dip204b-4nlw
LibName318=C:/Program Files/KiCad/share/library/dips082
LibName319=C:/Program Files/KiCad/share/library/display_ea_dog-m
LibName320=C:/Program Files/KiCad/share/library/display-kingbright
LibName321=C:/Program Files/KiCad/share/library/display-lcd
LibName322=C:/Program Files/KiCad/share/library/display-lcd-lxd
LibName323=C:/Program Files/KiCad/share/library/displayled8x8
LibName324=C:/Program Files/KiCad/share/library/displaytech_(chr)
LibName325=C:/Program Files/KiCad/share/library/divers
LibName326=C:/Program Files/KiCad/share/library/dodolcd
LibName327=C:/Program Files/KiCad/share/library/dodomicro
LibName328=C:/Program Files/KiCad/share/library/dome-key
LibName329=C:/Program Files/KiCad/share/library/dpads
LibName330=C:/Program Files/KiCad/share/library/dports
LibName331=C:/Program Files/KiCad/share/library/ds(s)30655
LibName332=C:/Program Files/KiCad/share/library/ds1307_pcf8583
LibName333=C:/Program Files/KiCad/share/library/ds1813_revised
LibName334=C:/Program Files/KiCad/share/library/dsp_texas
LibName335=C:/Program Files/KiCad/share/library/dsp56f8323
LibName336=C:/Program Files/KiCad/share/library/dsp56f8346
LibName337=C:/Program Files/KiCad/share/library/dsymbols
LibName338=C:/Program Files/KiCad/share/library/ecl
LibName339=C:/Program Files/KiCad/share/library/edge-156
LibName340=C:/Program Files/KiCad/share/library/elm
LibName341=C:/Program Files/KiCad/share/library/Elma
LibName342=C:/Program Files/KiCad/share/library/ember
LibName343=C:/Program Files/KiCad/share/library/emerging
LibName344=C:/Program Files/KiCad/share/library/enfora_module
LibName345=C:/Program Files/KiCad/share/library/EP_molex_6410_7395
LibName346=C:/Program Files/KiCad/share/library/ep_molex_6410_7395-02
LibName347=C:/Program Files/KiCad/share/library/er400trs
LibName348=C:/Program Files/KiCad/share/library/etx-board
LibName349=C:/Program Files/KiCad/share/library/ev9200g
LibName350=C:/Program Files/KiCad/share/library/everlight
LibName351=C:/Program Files/KiCad/share/library/evision
LibName352=C:/Program Files/KiCad/share/library/fairchild-tinylogic
LibName353=C:/Program Files/KiCad/share/library/fetky
LibName354=C:/Program Files/KiCad/share/library/fichte_div
LibName355=C:/Program Files/KiCad/share/library/filter-coilcraft
LibName356=C:/Program Files/KiCad/share/library/fitre
LibName357=C:/Program Files/KiCad/share/library/flashmemory
LibName358=C:/Program Files/KiCad/share/library/freescale-accelerometer
LibName359=C:/Program Files/KiCad/share/library/freescale-mc68hc908jb
LibName360=C:/Program Files/KiCad/share/library/fsoncore
LibName361=C:/Program Files/KiCad/share/library/ft8u100ax
LibName362=C:/Program Files/KiCad/share/library/ft2232c
LibName363=C:/Program Files/KiCad/share/library/ftdi
LibName364=C:/Program Files/KiCad/share/library/ftdi2
LibName365=C:/Program Files/KiCad/share/library/ftdi3
LibName366=C:/Program Files/KiCad/share/library/ftdi4
LibName367=C:/Program Files/KiCad/share/library/ftdichip
LibName368=C:/Program Files/KiCad/share/library/ftdichip-1
LibName369=C:/Program Files/KiCad/share/library/ftdichip-2
LibName370=C:/Program Files/KiCad/share/library/ftdichip-3
LibName371=C:/Program Files/KiCad/share/library/fze1066
LibName372=C:/Program Files/KiCad/share/library/gameboy
LibName373=C:/Program Files/KiCad/share/library/gm862
LibName374=C:/Program Files/KiCad/share/library/gpsms1
LibName375=C:/Program Files/KiCad/share/library/hacesoft
LibName376=C:/Program Files/KiCad/share/library/HBridge
LibName377=C:/Program Files/KiCad/share/library/HD15_B
LibName378=C:/Program Files/KiCad/share/library/hdsp
LibName379=C:/Program Files/KiCad/share/library/heatsink-aavid
LibName380=C:/Program Files/KiCad/share/library/hirose
LibName381=C:/Program Files/KiCad/share/library/hirose2
LibName382=C:/Program Files/KiCad/share/library/hirose-fx2-100
LibName383=C:/Program Files/KiCad/share/library/hirose-fx2-100-2
LibName384=C:/Program Files/KiCad/share/library/holtek
LibName385=C:/Program Files/KiCad/share/library/honda2-0
LibName386=C:/Program Files/KiCad/share/library/HONEYWEL
LibName387=C:/Program Files/KiCad/share/library/HONY3000
LibName388=C:/Program Files/KiCad/share/library/HONY4000
LibName389=C:/Program Files/KiCad/share/library/hopf
LibName390=C:/Program Files/KiCad/share/library/i2c
LibName391=C:/Program Files/KiCad/share/library/i2c_95xx
LibName392=C:/Program Files/KiCad/share/library/ibe_lbr
LibName393=C:/Program Files/KiCad/share/library/ic-bbd
LibName394=C:/Program Files/KiCad/share/library/ics512
LibName395=C:/Program Files/KiCad/share/library/ieee488
LibName396=C:/Program Files/KiCad/share/library/inductor-coilcraft
LibName397=C:/Program Files/KiCad/share/library/inductor-nkl
LibName398=C:/Program Files/KiCad/share/library/inductors-jwmiller
LibName399=C:/Program Files/KiCad/share/library/inductor-toko
LibName400=C:/Program Files/KiCad/share/library/infineon
LibName401=C:/Program Files/KiCad/share/library/infineon_tle_power
LibName402=C:/Program Files/KiCad/share/library/infineon-tricore
LibName403=C:/Program Files/KiCad/share/library/intel-strongarm
LibName404=C:/Program Files/KiCad/share/library/interface
LibName405=C:/Program Files/KiCad/share/library/intersil
LibName406=C:/Program Files/KiCad/share/library/inventronik
LibName407=C:/Program Files/KiCad/share/library/io-warrior
LibName408=C:/Program Files/KiCad/share/library/ipc-7351-capacitor
LibName409=C:/Program Files/KiCad/share/library/ipc-7351-diode
LibName410=C:/Program Files/KiCad/share/library/ipc-7351-inductor
LibName411=C:/Program Files/KiCad/share/library/ipc-7351-resistor
LibName412=C:/Program Files/KiCad/share/library/ipc-7351-transistor
LibName413=C:/Program Files/KiCad/share/library/ir2112
LibName414=C:/Program Files/KiCad/share/library/irf
LibName415=C:/Program Files/KiCad/share/library/irf-2
LibName416=C:/Program Files/KiCad/share/library/is61c1024al
LibName417=C:/Program Files/KiCad/share/library/is471f
LibName418=C:/Program Files/KiCad/share/library/isabellen
LibName419=C:/Program Files/KiCad/share/library/isd
LibName420=C:/Program Files/KiCad/share/library/isd-new
LibName421=C:/Program Files/KiCad/share/library/isd-new-1
LibName422=C:/Program Files/KiCad/share/library/ite-it81xx
LibName423=C:/Program Files/KiCad/share/library/jensen
LibName424=C:/Program Files/KiCad/share/library/jfw-pwm1
LibName425=C:/Program Files/KiCad/share/library/jst_eph
LibName426=C:/Program Files/KiCad/share/library/jst-ph
LibName427=C:/Program Files/KiCad/share/library/jt9s-1p
LibName428=C:/Program Files/KiCad/share/library/jumper
LibName429=C:/Program Files/KiCad/share/library/KEY_B
LibName430=C:/Program Files/KiCad/share/library/keypad4x4_ece
LibName431=C:/Program Files/KiCad/share/library/keystone
LibName432=C:/Program Files/KiCad/share/library/kingbright
LibName433=C:/Program Files/KiCad/share/library/kingfont_sdcmf10915w010
LibName434=C:/Program Files/KiCad/share/library/kingfont_sdcmf10915w010_covek
LibName435=C:/Program Files/KiCad/share/library/Knitter-Switch
LibName436=C:/Program Files/KiCad/share/library/kzh20_lithium_batterie_holder
LibName437=C:/Program Files/KiCad/share/library/l293e
LibName438=C:/Program Files/KiCad/share/library/l4960
LibName439=C:/Program Files/KiCad/share/library/l5973d
LibName440=C:/Program Files/KiCad/share/library/l6219
LibName441=C:/Program Files/KiCad/share/library/laipac_technologie
LibName442=C:/Program Files/KiCad/share/library/lasser
LibName443=C:/Program Files/KiCad/share/library/lattice
LibName444=C:/Program Files/KiCad/share/library/lcd_2x16_led_backlight
LibName445=C:/Program Files/KiCad/share/library/lcd_128x64_led_backlight
LibName446=C:/Program Files/KiCad/share/library/lcd_modules_ece
LibName447=C:/Program Files/KiCad/share/library/lcd_n3200_lph7677
LibName448=C:/Program Files/KiCad/share/library/lcd_nokia_6100
LibName449=C:/Program Files/KiCad/share/library/lcd_parallel
LibName450=C:/Program Files/KiCad/share/library/led
LibName451=C:/Program Files/KiCad/share/library/led_rgb
LibName452=C:/Program Files/KiCad/share/library/lexx
LibName453=C:/Program Files/KiCad/share/library/lf2403
LibName454=C:/Program Files/KiCad/share/library/linear2
LibName455=C:/Program Files/KiCad/share/library/linear3
LibName456=C:/Program Files/KiCad/share/library/linear4
LibName457=C:/Program Files/KiCad/share/library/linear-technology
LibName458=C:/Program Files/KiCad/share/library/linear-technology-2
LibName459=C:/Program Files/KiCad/share/library/linear-technology-3
LibName460=C:/Program Files/KiCad/share/library/linkup-l1110
LibName461=C:/Program Files/KiCad/share/library/little-logic
LibName462=C:/Program Files/KiCad/share/library/llk5_library
LibName463=C:/Program Files/KiCad/share/library/lm393d
LibName464=C:/Program Files/KiCad/share/library/lm1881
LibName465=C:/Program Files/KiCad/share/library/lm2937
LibName466=C:/Program Files/KiCad/share/library/lmd1820x
LibName467=C:/Program Files/KiCad/share/library/lmh1251
LibName468=C:/Program Files/KiCad/share/library/lmopamp
LibName469=C:/Program Files/KiCad/share/library/logo_ru
LibName470=C:/Program Files/KiCad/share/library/lp2986im-33
LibName471=C:/Program Files/KiCad/share/library/lp2989-so8
LibName472=C:/Program Files/KiCad/share/library/lpc210x
LibName473=C:/Program Files/KiCad/share/library/lpc213x
LibName474=C:/Program Files/KiCad/share/library/lph-7366
LibName475=C:/Program Files/KiCad/share/library/ltc_swr
LibName476=C:/Program Files/KiCad/share/library/ltc6900
LibName477=C:/Program Files/KiCad/share/library/ltd5122
LibName478=C:/Program Files/KiCad/share/library/lucorca
LibName479=C:/Program Files/KiCad/share/library/lumiled
LibName480=C:/Program Files/KiCad/share/library/lumiled-2
LibName481=C:/Program Files/KiCad/share/library/luminary-micro
LibName482=C:/Program Files/KiCad/share/library/lundahl
LibName483=C:/Program Files/KiCad/share/library/lvds
LibName484=C:/Program Files/KiCad/share/library/lvds-2
LibName485=C:/Program Files/KiCad/share/library/matsusada
LibName486=C:/Program Files/KiCad/share/library/max187
LibName487=C:/Program Files/KiCad/share/library/max232ti
LibName488=C:/Program Files/KiCad/share/library/max232ti_n
LibName489=C:/Program Files/KiCad/share/library/max498
LibName490=C:/Program Files/KiCad/share/library/max696x
LibName491=C:/Program Files/KiCad/share/library/max882_883_884
LibName492=C:/Program Files/KiCad/share/library/max882-smd
LibName493=C:/Program Files/KiCad/share/library/max1480-90
LibName494=C:/Program Files/KiCad/share/library/max1678
LibName495=C:/Program Files/KiCad/share/library/max1811
LibName496=C:/Program Files/KiCad/share/library/max3235ecwp
LibName497=C:/Program Files/KiCad/share/library/maxim
LibName498=C:/Program Files/KiCad/share/library/maxim-2
LibName499=C:/Program Files/KiCad/share/library/maxim-3
LibName500=C:/Program Files/KiCad/share/library/maxim-4
LibName501=C:/Program Files/KiCad/share/library/maxim-5
LibName502=C:/Program Files/KiCad/share/library/maxim-6
LibName503=C:/Program Files/KiCad/share/library/maxim-6a
LibName504=C:/Program Files/KiCad/share/library/maxim-6b
LibName505=C:/Program Files/KiCad/share/library/maxim-7
LibName506=C:/Program Files/KiCad/share/library/maxim-7a
LibName507=C:/Program Files/KiCad/share/library/maxim-8
LibName508=C:/Program Files/KiCad/share/library/maxim-9
LibName509=C:/Program Files/KiCad/share/library/maxim-10
LibName510=C:/Program Files/KiCad/share/library/maxim1719-21
LibName511=C:/Program Files/KiCad/share/library/maxim-filter
LibName512=C:/Program Files/KiCad/share/library/mc9s12ne64-lqfp112
LibName513=C:/Program Files/KiCad/share/library/mc68ez328
LibName514=C:/Program Files/KiCad/share/library/mc78l08a
LibName515=C:/Program Files/KiCad/share/library/mc3479p
LibName516=C:/Program Files/KiCad/share/library/mc33201d
LibName517=C:/Program Files/KiCad/share/library/mc33202d
LibName518=C:/Program Files/KiCad/share/library/mc33269
LibName519=C:/Program Files/KiCad/share/library/mc33269dt
LibName520=C:/Program Files/KiCad/share/library/mc34063
LibName521=C:/Program Files/KiCad/share/library/mcp120-130
LibName522=C:/Program Files/KiCad/share/library/mcp3304
LibName523=C:/Program Files/KiCad/share/library/memory-bsi
LibName524=C:/Program Files/KiCad/share/library/memory-intel
LibName525=C:/Program Files/KiCad/share/library/memory-samsung
LibName526=C:/Program Files/KiCad/share/library/Mentor-FEL
LibName527=C:/Program Files/KiCad/share/library/micrel
LibName528=C:/Program Files/KiCad/share/library/micro-68x_db
LibName529=C:/Program Files/KiCad/share/library/microchip
LibName530=C:/Program Files/KiCad/share/library/microchip_can
LibName531=C:/Program Files/KiCad/share/library/microchip_enet
LibName532=C:/Program Files/KiCad/share/library/microchip_mcp2120
LibName533=C:/Program Files/KiCad/share/library/microchip_pic16f716
LibName534=C:/Program Files/KiCad/share/library/microchip_tc7660
LibName535=C:/Program Files/KiCad/share/library/microchip-2
LibName536=C:/Program Files/KiCad/share/library/microchip-3
LibName537=C:/Program Files/KiCad/share/library/microchip-4
LibName538=C:/Program Files/KiCad/share/library/microchip-5
LibName539=C:/Program Files/KiCad/share/library/microchip16c7xx
LibName540=C:/Program Files/KiCad/share/library/microchip-16f688
LibName541=C:/Program Files/KiCad/share/library/microchip-18f258
LibName542=C:/Program Files/KiCad/share/library/microchip-dspic
LibName543=C:/Program Files/KiCad/share/library/microchip-enc28j60
LibName544=C:/Program Files/KiCad/share/library/microchip-mcp125x-xxx
LibName545=C:/Program Files/KiCad/share/library/microchip-pic18fxx5x
LibName546=C:/Program Files/KiCad/share/library/microchip-pic24
LibName547=C:/Program Files/KiCad/share/library/micro-codemercenaries
LibName548=C:/Program Files/KiCad/share/library/micro-fujitsu
LibName549=C:/Program Files/KiCad/share/library/micro-philips
LibName550=C:/Program Files/KiCad/share/library/micro-pic18xxx
LibName551=C:/Program Files/KiCad/share/library/micro-rabbit
LibName552=C:/Program Files/KiCad/share/library/micro-silabs
LibName553=C:/Program Files/KiCad/share/library/mini_din
LibName554=C:/Program Files/KiCad/share/library/minicir
LibName555=C:/Program Files/KiCad/share/library/minicircuits
LibName556=C:/Program Files/KiCad/share/library/minickts
LibName557=C:/Program Files/KiCad/share/library/minipci
LibName558=C:/Program Files/KiCad/share/library/mitel
LibName559=C:/Program Files/KiCad/share/library/mitsubishi_mcu
LibName560=C:/Program Files/KiCad/share/library/mma7260_7261
LibName561=C:/Program Files/KiCad/share/library/motordrv
LibName562=C:/Program Files/KiCad/share/library/motorola_hc08
LibName563=C:/Program Files/KiCad/share/library/motorola-video
LibName564=C:/Program Files/KiCad/share/library/mp3h6115a
LibName565=C:/Program Files/KiCad/share/library/m-pad-2.1
LibName566=C:/Program Files/KiCad/share/library/mpc5200
LibName567=C:/Program Files/KiCad/share/library/mpc8250
LibName568=C:/Program Files/KiCad/share/library/mpx4100a
LibName569=C:/Program Files/KiCad/share/library/mpxh6400
LibName570=C:/Program Files/KiCad/share/library/msp430
LibName571=C:/Program Files/KiCad/share/library/msp430-1
LibName572=C:/Program Files/KiCad/share/library/mt9t001
LibName573=C:/Program Files/KiCad/share/library/mt88xx
LibName574=C:/Program Files/KiCad/share/library/muratanfe61
LibName575=C:/Program Files/KiCad/share/library/murata-resonators
LibName576=C:/Program Files/KiCad/share/library/nais_tq2sa_smd_relay
LibName577=C:/Program Files/KiCad/share/library/nasem_adcs
LibName578=C:/Program Files/KiCad/share/library/national
LibName579=C:/Program Files/KiCad/share/library/national_cp3000
LibName580=C:/Program Files/KiCad/share/library/national_gaui
LibName581=C:/Program Files/KiCad/share/library/national-2
LibName582=C:/Program Files/KiCad/share/library/ncp5009
LibName583=C:/Program Files/KiCad/share/library/nec-upd71055
LibName584=C:/Program Files/KiCad/share/library/ni_gpib
LibName585=C:/Program Files/KiCad/share/library/nichia
LibName586=C:/Program Files/KiCad/share/library/nitron
LibName587=C:/Program Files/KiCad/share/library/nixie_tube
LibName588=C:/Program Files/KiCad/share/library/nordic-semi
LibName589=C:/Program Files/KiCad/share/library/nrf24l01
LibName590=C:/Program Files/KiCad/share/library/nxp
LibName591=C:/Program Files/KiCad/share/library/oldchips
LibName592=C:/Program Files/KiCad/share/library/op-amp
LibName593=C:/Program Files/KiCad/share/library/opt301m
LibName594=C:/Program Files/KiCad/share/library/optocoupler
LibName595=C:/Program Files/KiCad/share/library/optocoupler-2
LibName596=C:/Program Files/KiCad/share/library/opto-resistor
LibName597=C:/Program Files/KiCad/share/library/osman-pic16f62x
LibName598=C:/Program Files/KiCad/share/library/padsim
LibName599=C:/Program Files/KiCad/share/library/parallax_propeller
LibName600=C:/Program Files/KiCad/share/library/pbno_m
LibName601=C:/Program Files/KiCad/share/library/pca82c250
LibName602=C:/Program Files/KiCad/share/library/pcf8575c
LibName603=C:/Program Files/KiCad/share/library/PGA2310
LibName604=C:/Program Files/KiCad/share/library/philips
LibName605=C:/Program Files/KiCad/share/library/philips_gaui
LibName606=C:/Program Files/KiCad/share/library/philips_lpc21xx
LibName607=C:/Program Files/KiCad/share/library/philips1
LibName608=C:/Program Files/KiCad/share/library/philips-2
LibName609=C:/Program Files/KiCad/share/library/philips-3
LibName610=C:/Program Files/KiCad/share/library/philips-4
LibName611=C:/Program Files/KiCad/share/library/philips-5
LibName612=C:/Program Files/KiCad/share/library/philips-6
LibName613=C:/Program Files/KiCad/share/library/phoenix_gicv-gf
LibName614=C:/Program Files/KiCad/share/library/phytec
LibName615=C:/Program Files/KiCad/share/library/pic16f6xx
LibName616=C:/Program Files/KiCad/share/library/pic16f6xx_14pin
LibName617=C:/Program Files/KiCad/share/library/pic16f6xx-1
LibName618=C:/Program Files/KiCad/share/library/pic16f87x
LibName619=C:/Program Files/KiCad/share/library/pic16f690
LibName620=C:/Program Files/KiCad/share/library/pic16f818
LibName621=C:/Program Files/KiCad/share/library/pic16f914
LibName622=C:/Program Files/KiCad/share/library/pic18f4x2
LibName623=C:/Program Files/KiCad/share/library/pic18f2320
LibName624=C:/Program Files/KiCad/share/library/pic18f4550
LibName625=C:/Program Files/KiCad/share/library/pic18f6680
LibName626=C:/Program Files/KiCad/share/library/pic18fxx20
LibName627=C:/Program Files/KiCad/share/library/pic18fxx20-2
LibName628=C:/Program Files/KiCad/share/library/pic18fxx20-fxx8
LibName629=C:/Program Files/KiCad/share/library/picaxe-2
LibName630=C:/Program Files/KiCad/share/library/picaxe-3
LibName631=C:/Program Files/KiCad/share/library/picogate
LibName632=C:/Program Files/KiCad/share/library/picolight-msa
LibName633=C:/Program Files/KiCad/share/library/pictiva
LibName634=C:/Program Files/KiCad/share/library/piher
LibName635=C:/Program Files/KiCad/share/library/pinhead
LibName636=C:/Program Files/KiCad/share/library/pinhead-1
LibName637=C:/Program Files/KiCad/share/library/pixaxe28x
LibName638=C:/Program Files/KiCad/share/library/planartransformer
LibName639=C:/Program Files/KiCad/share/library/platinen
LibName640=C:/Program Files/KiCad/share/library/pneumatic
LibName641=C:/Program Files/KiCad/share/library/polyswitch_smd
LibName642=C:/Program Files/KiCad/share/library/Pot
LibName643=C:/Program Files/KiCad/share/library/powerconnectorskt
LibName644=C:/Program Files/KiCad/share/library/Power-in
LibName645=C:/Program Files/KiCad/share/library/promiesd02
LibName646=C:/Program Files/KiCad/share/library/propeller
LibName647=C:/Program Files/KiCad/share/library/pswitch40
LibName648=C:/Program Files/KiCad/share/library/ptc-littlefuse
LibName649=C:/Program Files/KiCad/share/library/ptn78060wah
LibName650=C:/Program Files/KiCad/share/library/pulse-eng
LibName651=C:/Program Files/KiCad/share/library/ramtron
LibName652=C:/Program Files/KiCad/share/library/ramtron-1
LibName653=C:/Program Files/KiCad/share/library/ramtron-2
LibName654=C:/Program Files/KiCad/share/library/raritaeten
LibName655=C:/Program Files/KiCad/share/library/RC2000M
LibName656=C:/Program Files/KiCad/share/library/rcl
LibName657=C:/Program Files/KiCad/share/library/rcl-2
LibName658=C:/Program Files/KiCad/share/library/rcm2200
LibName659=C:/Program Files/KiCad/share/library/rcm3000
LibName660=C:/Program Files/KiCad/share/library/rcm3360
LibName661=C:/Program Files/KiCad/share/library/rcm3400_module
LibName662=C:/Program Files/KiCad/share/library/rc-master
LibName663=C:/Program Files/KiCad/share/library/rc-master-smd
LibName664=C:/Program Files/KiCad/share/library/rds-decoder
LibName665=C:/Program Files/KiCad/share/library/ref-packages
LibName666=C:/Program Files/KiCad/share/library/relay
LibName667=C:/Program Files/KiCad/share/library/relay_finder
LibName668=C:/Program Files/KiCad/share/library/relay-pickering
LibName669=C:/Program Files/KiCad/share/library/renesas
LibName670=C:/Program Files/KiCad/share/library/renesas_mcu
LibName671=C:/Program Files/KiCad/share/library/renesas_mcu20
LibName672=C:/Program Files/KiCad/share/library/renesas21
LibName673=C:/Program Files/KiCad/share/library/resistor-bourns
LibName674=C:/Program Files/KiCad/share/library/resistor-ruf
LibName675=C:/Program Files/KiCad/share/library/rfm-ash
LibName676=C:/Program Files/KiCad/share/library/rfm-ash-02
LibName677=C:/Program Files/KiCad/share/library/rf-micro-devices
LibName678=C:/Program Files/KiCad/share/library/rfpic
LibName679=C:/Program Files/KiCad/share/library/rjmg-6xxx-8x-01
LibName680=C:/Program Files/KiCad/share/library/rtl8019as
LibName681=C:/Program Files/KiCad/share/library/russian-nixies
LibName682=C:/Program Files/KiCad/share/library/satcard
LibName683=C:/Program Files/KiCad/share/library/sawtek
LibName684=C:/Program Files/KiCad/share/library/scenix4
LibName685=C:/Program Files/KiCad/share/library/sena_technology-bluetooth
LibName686=C:/Program Files/KiCad/share/library/sfh511x
LibName687=C:/Program Files/KiCad/share/library/sfh920x
LibName688=C:/Program Files/KiCad/share/library/sgs-thom
LibName689=C:/Program Files/KiCad/share/library/sharp
LibName690=C:/Program Files/KiCad/share/library/sharp-arm
LibName691=C:/Program Files/KiCad/share/library/sht10_11_15
LibName692=C:/Program Files/KiCad/share/library/sht11
LibName693=C:/Program Files/KiCad/share/library/si-50014
LibName694=C:/Program Files/KiCad/share/library/sid_max
LibName695=C:/Program Files/KiCad/share/library/Siemens-Rel
LibName696=C:/Program Files/KiCad/share/library/silabs
LibName697=C:/Program Files/KiCad/share/library/silabs-2
LibName698=C:/Program Files/KiCad/share/library/silabs-eth
LibName699=C:/Program Files/KiCad/share/library/simmstik
LibName700=C:/Program Files/KiCad/share/library/sir-tfdu4100_tfds4500_tfdt4500
LibName701=C:/Program Files/KiCad/share/library/sl6270
LibName702=C:/Program Files/KiCad/share/library/smartcard
LibName703=C:/Program Files/KiCad/share/library/smartwed
LibName704=C:/Program Files/KiCad/share/library/smd-special
LibName705=C:/Program Files/KiCad/share/library/smsc
LibName706=C:/Program Files/KiCad/share/library/sn65lvds
LibName707=C:/Program Files/KiCad/share/library/sn74v293
LibName708=C:/Program Files/KiCad/share/library/sn2032
LibName709=C:/Program Files/KiCad/share/library/special-diodes
LibName710=C:/Program Files/KiCad/share/library/st_psd8xxfx
LibName711=C:/Program Files/KiCad/share/library/st_psd813
LibName712=C:/Program Files/KiCad/share/library/st232_gaui
LibName713=C:/Program Files/KiCad/share/library/st2221x
LibName714=C:/Program Files/KiCad/share/library/st7540
LibName715=C:/Program Files/KiCad/share/library/standingfet
LibName716=C:/Program Files/KiCad/share/library/stepper
LibName717=C:/Program Files/KiCad/share/library/st-l6208
LibName718=C:/Program Files/KiCad/share/library/st-microelectronics
LibName719=C:/Program Files/KiCad/share/library/str711
LibName720=C:/Program Files/KiCad/share/library/st-tda7375
LibName721=C:/Program Files/KiCad/share/library/stuart
LibName722=C:/Program Files/KiCad/share/library/stv_conec_dlsnyyan23x
LibName723=C:/Program Files/KiCad/share/library/stv_mk3ds1
LibName724=C:/Program Files/KiCad/share/library/supply
LibName725=C:/Program Files/KiCad/share/library/supply0
LibName726=C:/Program Files/KiCad/share/library/supply1
LibName727=C:/Program Files/KiCad/share/library/switch-copal
LibName728=C:/Program Files/KiCad/share/library/switch-misc
LibName729=C:/Program Files/KiCad/share/library/switch-tact
LibName730=C:/Program Files/KiCad/share/library/sx2_epf10k10a_epc2_c6713
LibName731=C:/Program Files/KiCad/share/library/t6963
LibName732=C:/Program Files/KiCad/share/library/tc4sxx-eu
LibName733=C:/Program Files/KiCad/share/library/tc65_siemens
LibName734=C:/Program Files/KiCad/share/library/tca0372dw
LibName735=C:/Program Files/KiCad/share/library/tcm3105
LibName736=C:/Program Files/KiCad/share/library/tda1562q
LibName737=C:/Program Files/KiCad/share/library/tda7386
LibName738=C:/Program Files/KiCad/share/library/tda7496l
LibName739=C:/Program Files/KiCad/share/library/tda8560q
LibName740=C:/Program Files/KiCad/share/library/tda8708a
LibName741=C:/Program Files/KiCad/share/library/termosensor
LibName742=C:/Program Files/KiCad/share/library/tex
LibName743=C:/Program Files/KiCad/share/library/tex2
LibName744=C:/Program Files/KiCad/share/library/texas
LibName745=C:/Program Files/KiCad/share/library/texas-msp
LibName746=C:/Program Files/KiCad/share/library/that_2252_rms_detector
LibName747=C:/Program Files/KiCad/share/library/that2180_sip8
LibName748=C:/Program Files/KiCad/share/library/that-corp
LibName749=C:/Program Files/KiCad/share/library/ti_msc1210
LibName750=C:/Program Files/KiCad/share/library/ti_msp430
LibName751=C:/Program Files/KiCad/share/library/ti_scope
LibName752=C:/Program Files/KiCad/share/library/ti6713bpyp
LibName753=C:/Program Files/KiCad/share/library/tiger
LibName754=C:/Program Files/KiCad/share/library/ti-msp430f14x1
LibName755=C:/Program Files/KiCad/share/library/tip112
LibName756=C:/Program Files/KiCad/share/library/tlv320aic23b
LibName757=C:/Program Files/KiCad/share/library/tmc
LibName758=C:/Program Files/KiCad/share/library/tmp10x
LibName759=C:/Program Files/KiCad/share/library/tms470
LibName760=C:/Program Files/KiCad/share/library/tms2402
LibName761=C:/Program Files/KiCad/share/library/tms2406
LibName762=C:/Program Files/KiCad/share/library/tms2808
LibName763=C:/Program Files/KiCad/share/library/tms2810
LibName764=C:/Program Files/KiCad/share/library/top-switcher
LibName765=C:/Program Files/KiCad/share/library/toshiba
LibName766=C:/Program Files/KiCad/share/library/tpic
LibName767=C:/Program Files/KiCad/share/library/tps769xx
LibName768=C:/Program Files/KiCad/share/library/tps77633
LibName769=C:/Program Files/KiCad/share/library/tqm_hydra_xc_modul
LibName770=C:/Program Files/KiCad/share/library/traco
LibName771=C:/Program Files/KiCad/share/library/traco_tmr
LibName772=C:/Program Files/KiCad/share/library/tracop1
LibName773=C:/Program Files/KiCad/share/library/trafo-xicon
LibName774=C:/Program Files/KiCad/share/library/transformer-trigger
LibName775=C:/Program Files/KiCad/share/library/transil
LibName776=C:/Program Files/KiCad/share/library/transistor
LibName777=C:/Program Files/KiCad/share/library/transistor-arrays
LibName778=C:/Program Files/KiCad/share/library/transistor-fet
LibName779=C:/Program Files/KiCad/share/library/transistor-fet+irf7201
LibName780=C:/Program Files/KiCad/share/library/transistor-power
LibName781=C:/Program Files/KiCad/share/library/transistors_gaui
LibName782=C:/Program Files/KiCad/share/library/Transputers
LibName783=C:/Program Files/KiCad/share/library/triggered_devices
LibName784=C:/Program Files/KiCad/share/library/trinamic
LibName785=C:/Program Files/KiCad/share/library/ts72116tp-10
LibName786=C:/Program Files/KiCad/share/library/tsop
LibName787=C:/Program Files/KiCad/share/library/Tubes
LibName788=C:/Program Files/KiCad/share/library/tusb3x10
LibName789=C:/Program Files/KiCad/share/library/tusb3x10-1
LibName790=C:/Program Files/KiCad/share/library/tusb6250
LibName791=C:/Program Files/KiCad/share/library/ua9638
LibName792=C:/Program Files/KiCad/share/library/ubicom
LibName793=C:/Program Files/KiCad/share/library/ubicom_v2
LibName794=C:/Program Files/KiCad/share/library/u-blox
LibName795=C:/Program Files/KiCad/share/library/ucb1400
LibName796=C:/Program Files/KiCad/share/library/uc-dimm
LibName797=C:/Program Files/KiCad/share/library/uicc_card_reader
LibName798=C:/Program Files/KiCad/share/library/uln-udn
LibName799=C:/Program Files/KiCad/share/library/ultrasonic_transducer
LibName800=C:/Program Files/KiCad/share/library/ultrasonic_transducer-1
LibName801=C:/Program Files/KiCad/share/library/unipac
LibName802=C:/Program Files/KiCad/share/library/valves2
LibName803=C:/Program Files/KiCad/share/library/varistor
LibName804=C:/Program Files/KiCad/share/library/vishay
LibName805=C:/Program Files/KiCad/share/library/vishay_tsal4400_bpw85c
LibName806=C:/Program Files/KiCad/share/library/vishay-1
LibName807=C:/Program Files/KiCad/share/library/v-reg
LibName808=C:/Program Files/KiCad/share/library/v-reg-2
LibName809=C:/Program Files/KiCad/share/library/v-reg-fairchild
LibName810=C:/Program Files/KiCad/share/library/v-reg-lowdrop
LibName811=C:/Program Files/KiCad/share/library/vs10xx
LibName812=C:/Program Files/KiCad/share/library/vs1001
LibName813=C:/Program Files/KiCad/share/library/waveform
LibName814=C:/Program Files/KiCad/share/library/weid762
LibName815=C:/Program Files/KiCad/share/library/western-digital-devices
LibName816=C:/Program Files/KiCad/share/library/wima_c
LibName817=C:/Program Files/KiCad/share/library/winbond-w9021x
LibName818=C:/Program Files/KiCad/share/library/wolfson
LibName819=C:/Program Files/KiCad/share/library/wolleatmel
LibName820=C:/Program Files/KiCad/share/library/wuerth_elektronik_v5
LibName821=C:/Program Files/KiCad/share/library/wuerth-elektronik_v4
LibName822=C:/Program Files/KiCad/share/library/xbee_r1
LibName823=C:/Program Files/KiCad/share/library/xc2v1000fg456
LibName824=C:/Program Files/KiCad/share/library/xc3s200-tq144
LibName825=C:/Program Files/KiCad/share/library/xdr-dram-toshiba
LibName826=C:/Program Files/KiCad/share/library/xenpak-msa
LibName827=C:/Program Files/KiCad/share/library/xicor-eepot
LibName828=C:/Program Files/KiCad/share/library/XILINX
LibName829=C:/Program Files/KiCad/share/library/xilinx_spartan2e
LibName830=C:/Program Files/KiCad/share/library/xilinx_spartan3
LibName831=C:/Program Files/KiCad/share/library/xilinx_spartan3_virtex4_and_5
LibName832=C:/Program Files/KiCad/share/library/Xilinx_VirtexII
LibName833=C:/Program Files/KiCad/share/library/Xilinx_VirtexII_Pro
LibName834=C:/Program Files/KiCad/share/library/xilinx_virtexii-xc2v80&flashprom
LibName835=C:/Program Files/KiCad/share/library/xilinx_xc9572xl-tq100
LibName836=C:/Program Files/KiCad/share/library/xilinx-xc3sxxxe_vq100
LibName837=C:/Program Files/KiCad/share/library/xport
LibName838=C:/Program Files/KiCad/share/library/x-port
LibName839=C:/Program Files/KiCad/share/library/xtx-board
LibName840=C:/Program Files/KiCad/share/library/z8encore8k_v10
LibName841=C:/Program Files/KiCad/share/library/zettl
LibName842=C:/Program Files/KiCad/share/library/Zilog-eZ80-v1_0
LibName843=C:/Program Files/KiCad/share/library/Zilog-Z8-Encore-v1_1
LibName844=C:/Program Files/KiCad/share/library/zilog-z8-encore-v1_2a
LibName845=C:/Program Files/KiCad/share/library/Zilog-ZNEO-v1_0
LibName846=C:/Program Files/KiCad/share/library/zivapc
LibName847=C:/Program Files/KiCad/share/library/zx4125p
LibName848=valves
LibName849=capacitors
LibName850=connectors_molex_serial_53047-A123
LibName851=inductors
LibName852=muonde
LibName853=powerint
LibName854=smd_soic_packages
LibName855=smd_ssop_packages
LibName856=xbee/XBee/XBee
LibName857=contrib/Allegro_ACS754_ACS755_ACS756_HallCurrentSensor_RevA
LibName858=contrib/BNC-Sockets_RevA
LibName859=contrib/Buzzer_Beeper_RevA_25Oct2010
LibName860=contrib/Capacitors_SMD_RevA
LibName861=contrib/Capacitors_ThroughHole_RevA
LibName862=contrib/Choke_Axial_ThroughHole_RevB
LibName863=contrib/Choke_Radial_ThroughHole_C&D_Bobin_RevA
LibName864=contrib/Choke_SMD_RevB_28July2010
LibName865=contrib/Choke_Toroid_ThroughHole_RevB_06Aug2010
LibName866=contrib/CommonModeChoke_Wuerth_Type-WE-CMB_RevA_24Oct2010
LibName867=contrib/Crystals_RevB_25Apr2012
LibName868=contrib/DCDC-ACDC-Converter_RevC_20Jul2012
LibName869=contrib/Dioden_SMD_RevA_27July2010
LibName870=contrib/Dioden_ThroughHole_RevC
LibName871=contrib/Elko_ThroughHole_RevB-3_30Dec2011
LibName872=contrib/EuroBoardoutline_RevB
LibName873=contrib/Fiducials_RevB
LibName874=contrib/Footprint-Symbols_RevD
LibName875=contrib/Fuseholder_ThroughHole_RevD_24Feb2011
LibName876=contrib/Heatsinks_RevC
LibName877=contrib/Label_RevA_21Mar2011
LibName878=contrib/Measurement_Point_RevA
LibName879=contrib/Measurement-Scala_RevA
LibName880=contrib/Mechanical_Socket-Plug_DIN41612-Stuff_RevA
LibName881=contrib/MiniUniversalMate-N-LokSockets_13Aug2012
LibName882=contrib/MountingHole_RevA
LibName883=contrib/Neosid_Air-Coil_SML_HAMxx31A_HDMxx31A_RevA_25Apr2012
LibName884=contrib/Neosid_Filter_HF-Coil_25Apr2012
LibName885=contrib/Neosid_Inductor_21Apr2012
LibName886=contrib/Opto-Devices_RevC_30Apr2011
LibName887=contrib/Oscillator-Modul_RevA
LibName888=contrib/Pentawatt_RevB_30Apr2011
LibName889=contrib/Potentiometer_RevB_02Aug2010
LibName890=contrib/Printtrafo_CHK_RevA_04Aug2010
LibName891=contrib/Relay_ThroughHole_RevB
LibName892=contrib/Resistor_SMD_RevA
LibName893=contrib/Resistor_ThroughHole_RevB_22Apr2011
LibName894=contrib/Resistor_Universal-Experimental_RevA
LibName895=contrib/SC70-6_Housing_26Jul2012
LibName896=contrib/SI570_SI571_Oscillator_RevA_11Jun2012
LibName897=contrib/Socket_MOLEX-KK-System
LibName898=contrib/Socket_WAGO734_RevA
LibName899=contrib/SOT23_Diode_RevA_03Aug2010
LibName900=contrib/SOT23_Transistor_RevA_03Aug2010
LibName901=contrib/SOT143_SOT143R_Housing_26Jul2012
LibName902=contrib/TerminalBlock_WAGO236-RM5mm_RevA2
LibName903=contrib/TO-92-All-Free_RevB
LibName904=contrib/Transformer_ThroughHole_RevA
LibName905=contrib/TransformerSMPS_ThroughHole_RevA
LibName906=contrib/Transistor_TO-92-Bipolar-inline-narrow-oval_RevB
LibName907=contrib/Transistor_TO-92-Bipolar-inline-wide_RevB
LibName908=contrib/Transistor_TO-92-Bipolar-molded-narrow_RevB
LibName909=contrib/Transistor_TO-92-Bipolar-molded-narrow-oval_RevB
LibName910=contrib/Transistor_TO-92-Bipolar-molded-wide_RevB
LibName911=contrib/Transistor_TO-92-Bipolar-molded-wide-oval_RevB
LibName912=contrib/Transistor_TO-92-Bipolar-molded-wide-universal_RevB
LibName913=contrib/Transistor_TO-92-Bipolar-rugged_RevB
LibName914=contrib/Transistor_TO-92-FET_RevB
LibName915=contrib/Transistor_TO-220_RevA
LibName916=contrib/Transistor_TO-247_RevC
LibName917=contrib/TSOT6-MK06A-Housing_26Jul2012
LibName918=contrib/WireConnections-Bridges_RevA
LibName919=contrib/WirePads_RevA
